application: nom-noms
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.bottle
  secure: always

skip_files:
# defaults
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
# prevent default theme from overriding mine
- ^(bower_components/paper-styles/default-theme.html)$
